name: CI

on:
  push:
    branches:
      - '**'

jobs:
  ci-lint:
    uses: kornsupadej/nextjs-boilerplate/.github/workflows/lint.yaml@master
  ci-test:
    uses: kornsupadej/nextjs-boilerplate/.github/workflows/test.yaml@master
